<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Playfair Cipher</h1>
    <!-- DataTales Example -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Input Data</h6>
                </div>
                <div class="card-body mb-4">
                    <form action="<?php global $action; echo route_method($action) ?>" method="POST">
                        <div class="row">
                            <div class="col-md-6 offset-1">
                                <div class="row mt-3">
                                    <div class="col-sm-12">
                                        <label for="" class="form-control-label">Plain Text</label>
                                        <input type="text" style="text-transform: uppercase;" name="plaintext" class="form-control" required placeholder="Masukkan plaintext disini...">
                                    </div>
                                    <div class="col-sm-12 mt-3">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label for="" class="form-control-label">Key Text</label>
                                                <input type="text" style="text-transform: uppercase;" name="keyword" class="form-control" required placeholder="Masukkan kata kunci disini...">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="" class="form-control-label">Type</label>
                                                <select name="type" id="" class="form-control">
                                                    <option value="encrypt">ENCRYPT</option>
                                                    <option value="decrypt">DECRYPT</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="" class="form-control-label">&nbsp;</label>
                                        <button name="submit" class="btn btn-primary btn-block" type="submit">Submit</button>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="" class="form-control-label">&nbsp;</label>
                                        <button class="btn btn-secondary btn-block" type="reset">Reset</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 mt-5">
                                <div class="alert alert-success">
                                    <h5 class="alert-heading font-weight-bold">Note :</h5>
                                    <p>
                                        This method <b>has not been</b> fully successful until it produces plain text to encrypt text, this method can <b><i><u>only access until it detects pairs of letters in a square table</u></i></b> and cannot produce the results of the cipher text directly. <br>
                                        You can check the results of tables that have been generated by this application with the table at <a href="https://www.boxentriq.com/code-breaking/playfair-cipher"><u>Boxentriq</u></a> or <a href="https://planetcalc.com/7751/"><u>Planetcalc</u></a>. <br>
                                        <b><i>Thanks</i></b>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <?php
                if (isset($_POST['submit'])):
                    $plaintext = preg_replace('/\s/', '', trim(str_replace(" ", "", strtoupper(getPost('plaintext')))));
                    $keywordText = preg_replace('/\s/', '', trim(str_replace(" ", "", strtoupper(getPost('keyword')))));
                    $type = getPost('type');
                    
                    $lengthText = strlen($plaintext);

                    $rangeChar = range('A', 'Z');
                    $lengthChar = count($rangeChar);

                    //Convert string to array
                    $keyword = str_split($keywordText);
                    $unique = array_unique($keyword);
                    $newRange = array_unique(array_merge($unique, $rangeChar));
                    $newRange = array_diff($newRange, ['J']);

                    $index = 0;
                    $resultRange = [];
                    foreach ($newRange as $val) {
                        $resultRange[$index] = $val;
                        $index++;    
                    }

                    $plainTextResult = "";
                    $cipherTextResult = "";

                    $fifthArr = array_chunk($resultRange, 5);
                    $sixthArr = [];



                ?>
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Hasil</h6>
                    </div>
                    <div class="card-body mb-4">
                        <div class="row">
                            <div class="col-md-10 offset-1">
                                <div class="row mt-3">
                                    <div class="col-md-12">
                                        <table class="table table-bordered">
                                            <tr>
                                                <td class="text-center font-weight-bold bg-primary text-white">PLAIN TEXT</td>
                                                <?php for ($i = 0; $i < strlen($plaintext); $i++): ?>
                                                    <td class="text-center font-weight-bold"><?= $plaintext[$i] ?></td>
                                                <?php endfor ?>
                                            </tr>
                                        </table>
                                        <table class="table table-bordered">
                                            <tr>
                                                <td class="text-center font-weight-bold bg-primary text-white">KEY</td>
                                                <?php for ($i = 0; $i < strlen($keywordText); $i++): ?>
                                                    <td class="text-center font-weight-bold"><?= $keywordText[$i] ?></td>
                                                <?php endfor ?>
                                            </tr>
                                        </table>
                                        <table class="table table-bordered">
                                            <tr>
                                                <td class="text-center font-weight-bold bg-primary text-white">NEW</td>
                                                <?php for ($i = 0; $i < count($resultRange); $i++): ?>
                                                    <td class="text-center font-weight-bold"><?= $resultRange[$i] ?></td>
                                                <?php endfor ?>
                                            </tr>
                                        </table>
                                    </div>
                                    <div class="col-md-6">
                                        <table class="table table-bordered table-hover">
                                            <tr>
                                                <td class="text-center bg-success text-white" colspan="5">5x5 TABLE</td>
                                            </tr>
                                            <?php
                                                $firstElement = [];
                                                for ($i = 0; $i < count($fifthArr); $i++):
                                                    $firstElement = $fifthArr[0];
                                            ?>
                                                    <tr>
                                                        <?php
                                                            for ($x = 0; $x < count($fifthArr[$i]); $x++):
                                                                $sixthArr[$i][$x] = $fifthArr[$i][$x];
                                                        ?>
                                                            <td class="text-center"><?= $fifthArr[$i][$x] ?></td>
                                                        <?php endfor ?>
                                                    </tr>
                                            <?php
                                                array_push($sixthArr[$i], $fifthArr[$i][0]);
                                                endfor;
                                                array_push($firstElement, "");
                                                array_push($sixthArr, $firstElement);
                                            ?>
                                        </table>
                                    </div>
                                    <div class="col-md-6">
                                        <table class="table table-bordered table-hover">
                                            <tr>
                                                <td class="text-center bg-success text-white" colspan="6">EXPANDED TABLE</td>
                                            </tr>
                                            <?php foreach ($sixthArr as $rowArr): ?>
                                                <tr>
                                                <?php foreach ($rowArr as $val): ?>
                                                    <td class="text-center <?= ($val == "") ? "bg-primary" : ""; ?>"><?= $val; ?></td>    
                                                <?php endforeach ?>
                                                </tr>
                                            <?php endforeach ?>
                                        </table>
                                    </div>
                                    <?php
                                        $plaintext .= (strlen($plaintext) % 2 == 1) ? "Z" : "";
                                        $plainArr = str_split($plaintext);
                                        $coupledChar = array_chunk($plainArr, 2);
                                    ?>
                                    <table class="table table-bordered">
                                        <tr>
                                            <td class="text-center text-white bg-primary">SPLITTED</td>
                                            <?php foreach ($coupledChar as $char): ?>
                                                <td class="text-center"><?= implode($char, "") ?></td>
                                            <?php endforeach ?>
                                        </tr>
                                    </table>
                                    <div class="row">
                                        <?php foreach ($coupledChar as $char): ?>
                                            <div class="col-md-3">
                                                <table class="table table-bordered table-hover">
                                                    <tr>
                                                        <td class="text-center bg-success text-white" colspan="6">
                                                            <?php
                                                                $combineChar = implode($char, "");
                                                                echo $combineChar;

                                                                $combineChar[0] = ($combineChar[0] == "J") ? "I" : $combineChar[0];
                                                                $combineChar[1] = ($combineChar[1] == "J") ? "I" : $combineChar[1];
                                                                ?>
                                                        </td>
                                                    </tr>
                                                    <?php 
                                                    $index = 0;
                                                        for($i = 0; $i < count($sixthArr); $i++): ?>
                                                            <tr>
                                                            <?php
                                                            for($x = 0; $x < count($sixthArr[$i]); $x++):
                                                                $class = "";
                                                                if($index < 2):
                                                                    if($sixthArr[$i][$x] == $combineChar[0] || $sixthArr[$i][$x] == $combineChar[1]):
                                                                        $class = "bg-primary text-white";
                                                                        $index++;
                                                                    endif;

                                                                endif;

                                                                ?>
                                                                <td class="text-center <?= $class; ?>"><?= $sixthArr[$i][$x]; ?></td>
                                                            <?php
                                                            endfor ?>
                                                            </tr>
                                                    <?php endfor ?>
                                                </table>
                                            </div>
                                        <?php endforeach ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
